version: 1.0.{build}
environment:
  VCDIR: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\
  BOOST_ROOT: C:\Libraries\boost
  BOOST_INCLUDEDIR: C:\Libraries\boost
  BOOST_LIBRARYDIR: C:\Libraries\boost\lib32-msvc-12.0
build_script:
- "%VCDIR%"\vcvarsall.bat
- cmake -G "Visual Studio 12" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBOOST_INCLUDEDIR="%BOOST_INCLUDEDIR%" .
- msbuild /p:Configuration="Release" AppveyorTest.sln

artifacts:
- path: bin\Release\*.exe
  name: Appveyor-test

